local_costmap:
   global_frame: /map
   robot_base_frame: /base_link
   update_frequency: 3.0
   publish_frequency: 1.0
   rolling_window: true
   width: 6.0
   height: 6.0
   resolution: 0.05
   transform_tolerance: 1.0
   static_map: false ##  local_costmap don't have static layer

### obstacle_layer
   map_type: costmap  ## voxel another layer
   max_obstacle_height: 2.0
   min_obstacle_height: 0.2
   raytrace_range: 3.0
   obstacle_range: 2.5   ## local_costmap detect range
  # track_unknown_space:
   observation_sources: scan
   scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0}

### inflation_layer
    # cost_scaling_factor:
   inflation_radius: 0.15
